// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/boundary_logs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BoundaryLog represents a single boundary audit log entry.
// Field numbers MUST match coder's agent/proto/agent.proto to ensure
// wire format compatibility.
type BoundaryLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   []byte                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Allowed       bool                   `protobuf:"varint,3,opt,name=allowed,proto3" json:"allowed,omitempty"`
	HttpMethod    string                 `protobuf:"bytes,4,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	HttpUrl       string                 `protobuf:"bytes,5,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
	MatchedRule   string                 `protobuf:"bytes,6,opt,name=matched_rule,json=matchedRule,proto3" json:"matched_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundaryLog) Reset() {
	*x = BoundaryLog{}
	mi := &file_proto_boundary_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundaryLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryLog) ProtoMessage() {}

func (x *BoundaryLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boundary_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryLog.ProtoReflect.Descriptor instead.
func (*BoundaryLog) Descriptor() ([]byte, []int) {
	return file_proto_boundary_logs_proto_rawDescGZIP(), []int{0}
}

func (x *BoundaryLog) GetWorkspaceId() []byte {
	if x != nil {
		return x.WorkspaceId
	}
	return nil
}

func (x *BoundaryLog) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *BoundaryLog) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *BoundaryLog) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *BoundaryLog) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

func (x *BoundaryLog) GetMatchedRule() string {
	if x != nil {
		return x.MatchedRule
	}
	return ""
}

// BoundaryLogsRequest is sent to the agent socket.
// Field numbers MUST match coder's ReportBoundaryLogsRequest.
type BoundaryLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*BoundaryLog         `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundaryLogsRequest) Reset() {
	*x = BoundaryLogsRequest{}
	mi := &file_proto_boundary_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundaryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryLogsRequest) ProtoMessage() {}

func (x *BoundaryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boundary_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryLogsRequest.ProtoReflect.Descriptor instead.
func (*BoundaryLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_boundary_logs_proto_rawDescGZIP(), []int{1}
}

func (x *BoundaryLogsRequest) GetLogs() []*BoundaryLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_proto_boundary_logs_proto protoreflect.FileDescriptor

const file_proto_boundary_logs_proto_rawDesc = "" +
	"\n" +
	"\x19proto/boundary_logs.proto\x12\x0eboundary.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\vBoundaryLog\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\fR\vworkspaceId\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x18\n" +
	"\aallowed\x18\x03 \x01(\bR\aallowed\x12\x1f\n" +
	"\vhttp_method\x18\x04 \x01(\tR\n" +
	"httpMethod\x12\x19\n" +
	"\bhttp_url\x18\x05 \x01(\tR\ahttpUrl\x12!\n" +
	"\fmatched_rule\x18\x06 \x01(\tR\vmatchedRule\"F\n" +
	"\x13BoundaryLogsRequest\x12/\n" +
	"\x04logs\x18\x01 \x03(\v2\x1b.boundary.proto.BoundaryLogR\x04logsB!Z\x1fgithub.com/coder/boundary/protob\x06proto3"

var (
	file_proto_boundary_logs_proto_rawDescOnce sync.Once
	file_proto_boundary_logs_proto_rawDescData []byte
)

func file_proto_boundary_logs_proto_rawDescGZIP() []byte {
	file_proto_boundary_logs_proto_rawDescOnce.Do(func() {
		file_proto_boundary_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_boundary_logs_proto_rawDesc), len(file_proto_boundary_logs_proto_rawDesc)))
	})
	return file_proto_boundary_logs_proto_rawDescData
}

var file_proto_boundary_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_boundary_logs_proto_goTypes = []any{
	(*BoundaryLog)(nil),           // 0: boundary.proto.BoundaryLog
	(*BoundaryLogsRequest)(nil),   // 1: boundary.proto.BoundaryLogsRequest
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_boundary_logs_proto_depIdxs = []int32{
	2, // 0: boundary.proto.BoundaryLog.time:type_name -> google.protobuf.Timestamp
	0, // 1: boundary.proto.BoundaryLogsRequest.logs:type_name -> boundary.proto.BoundaryLog
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_boundary_logs_proto_init() }
func file_proto_boundary_logs_proto_init() {
	if File_proto_boundary_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_boundary_logs_proto_rawDesc), len(file_proto_boundary_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_boundary_logs_proto_goTypes,
		DependencyIndexes: file_proto_boundary_logs_proto_depIdxs,
		MessageInfos:      file_proto_boundary_logs_proto_msgTypes,
	}.Build()
	File_proto_boundary_logs_proto = out.File
	file_proto_boundary_logs_proto_goTypes = nil
	file_proto_boundary_logs_proto_depIdxs = nil
}
