// NOTE: BoundaryLog and BoundaryLogsRequest must stay wire-compatible with
// github.com/coder/coder/v2/agent/proto (BoundaryLog and ReportBoundaryLogsRequest)
// for communication over the Unix socket to the agent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/logs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoundaryLog struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Allowed bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Time    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to Resource:
	//
	//	*BoundaryLog_HttpRequest_
	Resource      isBoundaryLog_Resource `protobuf_oneof:"resource"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundaryLog) Reset() {
	*x = BoundaryLog{}
	mi := &file_proto_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundaryLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryLog) ProtoMessage() {}

func (x *BoundaryLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryLog.ProtoReflect.Descriptor instead.
func (*BoundaryLog) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0}
}

func (x *BoundaryLog) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *BoundaryLog) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *BoundaryLog) GetResource() isBoundaryLog_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *BoundaryLog) GetHttpRequest() *BoundaryLog_HttpRequest {
	if x != nil {
		if x, ok := x.Resource.(*BoundaryLog_HttpRequest_); ok {
			return x.HttpRequest
		}
	}
	return nil
}

type isBoundaryLog_Resource interface {
	isBoundaryLog_Resource()
}

type BoundaryLog_HttpRequest_ struct {
	HttpRequest *BoundaryLog_HttpRequest `protobuf:"bytes,3,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

func (*BoundaryLog_HttpRequest_) isBoundaryLog_Resource() {}

// BoundaryLogsRequest is sent to the agent socket.
// Field numbers MUST match coder's ReportBoundaryLogsRequest.
type BoundaryLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*BoundaryLog         `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundaryLogsRequest) Reset() {
	*x = BoundaryLogsRequest{}
	mi := &file_proto_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundaryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryLogsRequest) ProtoMessage() {}

func (x *BoundaryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryLogsRequest.ProtoReflect.Descriptor instead.
func (*BoundaryLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{1}
}

func (x *BoundaryLogsRequest) GetLogs() []*BoundaryLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type BoundaryLog_HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	MatchedRule   string                 `protobuf:"bytes,3,opt,name=matched_rule,json=matchedRule,proto3" json:"matched_rule,omitempty"` // Only populated when allowed = false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundaryLog_HttpRequest) Reset() {
	*x = BoundaryLog_HttpRequest{}
	mi := &file_proto_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundaryLog_HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryLog_HttpRequest) ProtoMessage() {}

func (x *BoundaryLog_HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryLog_HttpRequest.ProtoReflect.Descriptor instead.
func (*BoundaryLog_HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BoundaryLog_HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BoundaryLog_HttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BoundaryLog_HttpRequest) GetMatchedRule() string {
	if x != nil {
		return x.MatchedRule
	}
	return ""
}

var File_proto_logs_proto protoreflect.FileDescriptor

const file_proto_logs_proto_rawDesc = "" +
	"\n" +
	"\x10proto/logs.proto\x12\x11coder.boundary.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n" +
	"\vBoundaryLog\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12O\n" +
	"\fhttp_request\x18\x03 \x01(\v2*.coder.boundary.v1.BoundaryLog.HttpRequestH\x00R\vhttpRequest\x1aZ\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fmatched_rule\x18\x03 \x01(\tR\vmatchedRuleB\n" +
	"\n" +
	"\bresource\"I\n" +
	"\x13BoundaryLogsRequest\x122\n" +
	"\x04logs\x18\x01 \x03(\v2\x1e.coder.boundary.v1.BoundaryLogR\x04logsB!Z\x1fgithub.com/coder/boundary/protob\x06proto3"

var (
	file_proto_logs_proto_rawDescOnce sync.Once
	file_proto_logs_proto_rawDescData []byte
)

func file_proto_logs_proto_rawDescGZIP() []byte {
	file_proto_logs_proto_rawDescOnce.Do(func() {
		file_proto_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)))
	})
	return file_proto_logs_proto_rawDescData
}

var file_proto_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_logs_proto_goTypes = []any{
	(*BoundaryLog)(nil),             // 0: coder.boundary.v1.BoundaryLog
	(*BoundaryLogsRequest)(nil),     // 1: coder.boundary.v1.BoundaryLogsRequest
	(*BoundaryLog_HttpRequest)(nil), // 2: coder.boundary.v1.BoundaryLog.HttpRequest
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_proto_logs_proto_depIdxs = []int32{
	3, // 0: coder.boundary.v1.BoundaryLog.time:type_name -> google.protobuf.Timestamp
	2, // 1: coder.boundary.v1.BoundaryLog.http_request:type_name -> coder.boundary.v1.BoundaryLog.HttpRequest
	0, // 2: coder.boundary.v1.BoundaryLogsRequest.logs:type_name -> coder.boundary.v1.BoundaryLog
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_logs_proto_init() }
func file_proto_logs_proto_init() {
	if File_proto_logs_proto != nil {
		return
	}
	file_proto_logs_proto_msgTypes[0].OneofWrappers = []any{
		(*BoundaryLog_HttpRequest_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_logs_proto_goTypes,
		DependencyIndexes: file_proto_logs_proto_depIdxs,
		MessageInfos:      file_proto_logs_proto_msgTypes,
	}.Build()
	File_proto_logs_proto = out.File
	file_proto_logs_proto_goTypes = nil
	file_proto_logs_proto_depIdxs = nil
}
