// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: proto/logs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BoundaryLog represents a log for a single resource access processed
// by boundary.
type BoundaryLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether boundary allowed this resource access.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// The timestamp when boundary processed this resource access.
	Time *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// The resource being accessed by boundary.
	//
	// Types that are assignable to Resource:
	//
	//	*BoundaryLog_HttpRequest_
	Resource isBoundaryLog_Resource `protobuf_oneof:"resource"`
}

func (x *BoundaryLog) Reset() {
	*x = BoundaryLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoundaryLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryLog) ProtoMessage() {}

func (x *BoundaryLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryLog.ProtoReflect.Descriptor instead.
func (*BoundaryLog) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0}
}

func (x *BoundaryLog) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *BoundaryLog) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (m *BoundaryLog) GetResource() isBoundaryLog_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (x *BoundaryLog) GetHttpRequest() *BoundaryLog_HttpRequest {
	if x, ok := x.GetResource().(*BoundaryLog_HttpRequest_); ok {
		return x.HttpRequest
	}
	return nil
}

type isBoundaryLog_Resource interface {
	isBoundaryLog_Resource()
}

type BoundaryLog_HttpRequest_ struct {
	HttpRequest *BoundaryLog_HttpRequest `protobuf:"bytes,3,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

func (*BoundaryLog_HttpRequest_) isBoundaryLog_Resource() {}

// ReportBoundaryLogsRequest is a request to re-emit the given BoundaryLogs.
//
// NOTE: BoundaryLog and ReportBoundaryLogsRequest must stay wire-compatible with
// github.com/coder/boundary/proto/logs.proto which boundary uses to send logs
// over the Unix socket to the agent. This compatibility is hand-maintained for
// simplicity while boundary lives in a separate repository.
type ReportBoundaryLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*BoundaryLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *ReportBoundaryLogsRequest) Reset() {
	*x = ReportBoundaryLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportBoundaryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBoundaryLogsRequest) ProtoMessage() {}

func (x *ReportBoundaryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBoundaryLogsRequest.ProtoReflect.Descriptor instead.
func (*ReportBoundaryLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{1}
}

func (x *ReportBoundaryLogsRequest) GetLogs() []*BoundaryLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ReportBoundaryLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportBoundaryLogsResponse) Reset() {
	*x = ReportBoundaryLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportBoundaryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBoundaryLogsResponse) ProtoMessage() {}

func (x *ReportBoundaryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBoundaryLogsResponse.ProtoReflect.Descriptor instead.
func (*ReportBoundaryLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{2}
}

type BoundaryLog_HttpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// The rule that resulted in this HTTP request not being allowed.
	// Only populated when allowed = false.
	MatchedRule string `protobuf:"bytes,3,opt,name=matched_rule,json=matchedRule,proto3" json:"matched_rule,omitempty"`
}

func (x *BoundaryLog_HttpRequest) Reset() {
	*x = BoundaryLog_HttpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoundaryLog_HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryLog_HttpRequest) ProtoMessage() {}

func (x *BoundaryLog_HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryLog_HttpRequest.ProtoReflect.Descriptor instead.
func (*BoundaryLog_HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BoundaryLog_HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BoundaryLog_HttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BoundaryLog_HttpRequest) GetMatchedRule() string {
	if x != nil {
		return x.MatchedRule
	}
	return ""
}

var File_proto_logs_proto protoreflect.FileDescriptor

var file_proto_logs_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x02, 0x0a, 0x0b, 0x42, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64,
	0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x4f, 0x0a, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x4c, 0x6f, 0x67, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x5a, 0x0a, 0x0b, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x42, 0x0a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x4f, 0x0a, 0x19, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72,
	0x79, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_logs_proto_rawDescOnce sync.Once
	file_proto_logs_proto_rawDescData = file_proto_logs_proto_rawDesc
)

func file_proto_logs_proto_rawDescGZIP() []byte {
	file_proto_logs_proto_rawDescOnce.Do(func() {
		file_proto_logs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_logs_proto_rawDescData)
	})
	return file_proto_logs_proto_rawDescData
}

var file_proto_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_logs_proto_goTypes = []interface{}{
	(*BoundaryLog)(nil),                // 0: coder.boundary.v1.BoundaryLog
	(*ReportBoundaryLogsRequest)(nil),  // 1: coder.boundary.v1.ReportBoundaryLogsRequest
	(*ReportBoundaryLogsResponse)(nil), // 2: coder.boundary.v1.ReportBoundaryLogsResponse
	(*BoundaryLog_HttpRequest)(nil),    // 3: coder.boundary.v1.BoundaryLog.HttpRequest
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_proto_logs_proto_depIdxs = []int32{
	4, // 0: coder.boundary.v1.BoundaryLog.time:type_name -> google.protobuf.Timestamp
	3, // 1: coder.boundary.v1.BoundaryLog.http_request:type_name -> coder.boundary.v1.BoundaryLog.HttpRequest
	0, // 2: coder.boundary.v1.ReportBoundaryLogsRequest.logs:type_name -> coder.boundary.v1.BoundaryLog
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_logs_proto_init() }
func file_proto_logs_proto_init() {
	if File_proto_logs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_logs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoundaryLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportBoundaryLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportBoundaryLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoundaryLog_HttpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_logs_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BoundaryLog_HttpRequest_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_logs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_logs_proto_goTypes,
		DependencyIndexes: file_proto_logs_proto_depIdxs,
		MessageInfos:      file_proto_logs_proto_msgTypes,
	}.Build()
	File_proto_logs_proto = out.File
	file_proto_logs_proto_rawDesc = nil
	file_proto_logs_proto_goTypes = nil
	file_proto_logs_proto_depIdxs = nil
}
